### ISSUE TITLE
Dynamic domain name

### ISSUE THREAD

**Issue by sjhmt** [feathersjs/gitbook-plugin-feathers-versions#2]
Automatically identifies the current access domain name and supports the value of the variable definition "value" in the configuration file.

**Comment by daffl** [comment]
Hi @UPEMPEROR. I'm sorry but I am not following. This repository is for the version dropdown at https://docs.feathersjs.com and probably shouldn't be used anywhere else. Is there a problem with https://docs.feathersjs.com?

**Comment by sjhmt** [comment]
i am from 'https://plugins.gitbook.com/plugin/feathers-versions', and i think this plugin  is easy to adapt to dynamic domain names, such like this:
```
        $.each(versions, function(i, version) {
            var $option = $('<option>', {
                'selected': window.location.href.indexOf(version.value) >= 0,
                'value': version.value,
                'text': version.text
            });

            $option.appendTo($select);
        });

        $select.change(function() {
            var filtered = $.grep(versions, function(v) {
                return v.value === $select.val();
            });
            // Get actual version Object from array
            var version = filtered[0];
            window.location.href = version.value.indexOf("http") >= 0 ? version.value : (window.location.origin + version.value);
        });
```

**Comment by daffl** [comment]
Oh, yes, that would work. We are using full domains like https://auk.docs.feathersjs.com or https://legacy.docs.feathersjs.com for our different versions. You can fork the repository and adjust it to your needs it you would like to use it though.
